### ISSUE TITLE
Image optimization

### ISSUE THREAD

**Issue by alexcastano** [janko-m/image_processing#10]
Hello @janko-m ,

Did you think about add image optimization to this gem? Something like https://github.com/jtescher/image_optimizer

Thank you for your time

**Comment by janko-m** [comment]
ImageProcessing is meant to be a wrapper for processing images using certain gems. So `ImageProcessing::MiniMagick` is a wrapper around MiniMagick, a future `ImageProcessing::Vips` would be a wrapper around VIPS, and so on.

It doesn't make much sense for ImageProcessing gem to include a wrapper around [ImageOptim](https://github.com/toy/image_optim) or [ImageOptimizer](https://github.com/jtescher/image_optimizer) libraries, as it's simple enough to used them directly.

**Comment by alexcastano** [comment]
I see and it makes sense. I didn't know ImageOptim, great gem. Thank you!
