### ISSUE TITLE
Pass an argument to all Magick invocations

### ISSUE THREAD

**Issue by renchap** [janko-m/image_processing#11]
Is it a way to add an argument, in my case `-quiet`, to all invocations ?

A user uploaded a file taken with the Samsung app, and the JPEG is considered as malformed by libjpeg, ending up with this error: `mogrify: Invalid SOS parameters for sequential JPEG`
It is a known bug, and graphicmagick's maintainers advise to use `-quiet` to ignore them (for example here: https://sourceforge.net/p/graphicsmagick/bugs/385/)

Is it a way to do this for all image_processing calls?

**Comment by janko-m** [comment]
There is no way to do that at the moment, though I'm definitely open to adding such a feature.

**Comment by renchap** [comment]
How would you see it implemented?

I thought about a block-line implem but I am not sure this is possible:

```ruby
with_args([:quiet]) do
  resize_to_limit(...)
end
```

A global option could work but I am not sure I want to run with `-quiet` all the time, or what this implies regarding other possible errors.

Sidenote: did you already toyed with a VIPS-based implem?

**Comment by janko-m** [comment]
> How would you see it implemented?

Good question. If this could be added globally, then the solution would be easy – add an `ImageProcessing::MiniMagick.default_args` or something. However, if you want to add defaults for only a subset of commands, I would suggest simply passing a block to the commands. For example:

```rb
resize_to_limit(file1, 800, 800, &:quiet)
resize_to_limit(file2, 500, 500, &:quiet)
resize_to_limit(file3, 300, 300, &:quiet)
```

or 

```rb
suppress_warnings = -> (cmd) { cmd.quiet }

resize_to_limit(file1, 800, 800, &:suppress_warnings)
resize_to_limit(file2, 500, 500, &:suppress_warnings)
resize_to_limit(file3, 300, 300, &:suppress_warnings)
```

It would probably make sense to add a "default arguments" feature to MiniMagick itself, which could look like what you suggested, and should internally use thread-local variables for thread-safety:

```rb
MiniMagick.with_default_args("-quiet") do
  resize_to_limit(...)
end
```

> Sidenote: did you already toyed with a VIPS-based implem?

It has been on my TODO list, and I had already designed `image_processing` to make it easy to add other backends. As a matter of fact, @GustavoCaso has just started playing with a VIPS-based implementation. We've just discussed that, in addition to [ruby-vips](https://github.com/jcupitt/ruby-vips), we want to try to reuse [vips-process](https://github.com/dariocravero/vips-process) or [vips-thumbnail](https://github.com/ioquatix/vips-thumbnail), or at least use them as source of knowledge, including [carrierwave-vips](https://github.com/search?q=carrierwave-vips).

**Comment by janko-m** [comment]
Setting default arguments is trivial with the new chainable API that's currently on `master`:

```rb
pipeline = ImageProcessing::MiniMagick
  .source(image)
  .quiet

large  = pipeline.resize_to_limit!(800, 800)
medium = pipeline.resize_to_limit!(500, 500)
small  = pipeline.resize_to_limit!(300, 300)
```
