### ISSUE TITLE
Losing image EXIF information on convert?

### ISSUE THREAD

**Issue by adamthede** [janko-m/image_processing#13]
I'm using shrine and image_processing to manage image uploads.  I'm using the versions, processing, and add_metadata plugins.  I've got a custom metadata function for exif information.  It works fine when I don't convert images.  But if I use convert, I seem to lose EXIF data.  Is it possible that the convert method removes EXIF information?  This is happening for me when I upload and convert TIFF images to JPEGs.

Code is as follows:

``` 
 add_metadata :exif do |io, context|
    if ['.jpg', '.jpeg'].include? File.extname(io.path).downcase
      begin
        Exif::Data.new(io.path)
      rescue
        nil
      end
    elsif ['.tiff', '.tif'].include? File.extname(io.path).downcase
      data = EXIFR::TIFF.new(io.path)
      data
    end
  end
```

```
  process(:store) do |io, context|
    if ['image/jpg', 'image/jpeg', 'image/png', 'image/gif', 'image/tiff'].include? io.mime_type
      original = io.download

      if ['image/png', 'image/gif', 'image/tiff'].include? io.mime_type
        converted = convert(original, 'jpg')
      else
        converted = original
      end

      size_1200 = resize_to_limit!(converted , 1200, 1200) { |cmd| cmd.auto_orient }
      size_600 = resize_to_limit(size_1200,  600, 600)
      size_100 = resize_to_limit(size_600,  100, 100)

      {original: io, large: size_1200, medium: size_600, small: size_100}
    end
end
```

**Comment by hmistry** [comment]
@adamthede I haven't looked too deep into this but I suspect this might be an imagemagick issue more than image_processing. The latter is merely a wrapper but it may not include all the command line arguments to preserve EXIF data. 

Have you tried running imagemagick convert cli directly on your image to see if it looses the EXIF data or it's image_processing + minimagick wrapper that's loosing it?

**Comment by janko-m** [comment]
@adamthede If you google the ImageMagick forum questions, you'll see there are a few questions about why the EXIF data is lost in the conversion. The answer is that TIFF stores EXIF in its own way, and it isn't automatically copied to JPEG's EXIF format on conversion.

Can you confirm that this still happens on latest ImageMagick version? If yes, it would be great if you could find an ImageMagick solution to that, and then it can be ported to ImageProcessing::MiniMagick.

**Comment by janko-m** [comment]
I will close this, as I think this needs to be solved in ImageMagick itself, it's too complex to solve here. Apparently ImageMagick already [preserves](https://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=32681) some EXIF tags when converting from TIFF to EXIF, which means this functionality is indeed in ImageMagick's scope.
