### ISSUE TITLE
undefined method 'source' for ImageProcessing::MiniMagick:Module

### ISSUE THREAD

**Issue by andyrue** [janko-m/image_processing#19]
This has got to be something simple, but I can't seem to figure out what I'm doing wrong.

`processed = ImageProcessing::MiniMagick.source(old_presenter.photo)`

results in 

`NoMethodError: undefined method `source' for ImageProcessing::MiniMagick:Module`

Using version 0.9.0

**Comment by mokolabs** [comment]
One idea... is `old_presenter.photo` returning an IO object or the parent record that holds the attachment?

I believe it needs to be an IO object (file, etc.).

**Comment by andyrue** [comment]
Oh silly me. You are correct. Didn't realize it was a Paperclip::Attachment. Thank you!

**Comment by janko-m** [comment]
@andyrue The `ImageProcessing::MiniMagick` conversion to the chainable API hasn't yet been released, please use `master` for now.

**Comment by janko-m** [comment]
I've just released version 0.10.0 which switches over `ImageProcessing::MiniMagick` to the chainable API (and deprecates the old API).
