### ISSUE TITLE
Add crop?

### ISSUE THREAD

**Issue by paulgoetze** [janko-m/image_processing#2]
Hey, great work!

Would it make sense to add a `crop/crop!` method in [`mini_magick.rb`](https://github.com/janko-m/image_processing/blob/master/lib/image_processing/mini_magick.rb)? Maybe something like this?:

```ruby
def crop(image, x, y, x_offset, y_offset)
  with_minimagick(image) do |img|
    img.combine_options do |cmd|
      yield cmd if block_given?
      cmd.crop "#{x}x#{y}+#{x_offset}+#{y_offset}!"
    end
  end
end
nondestructive_alias :crop, :crop!
```

I just found myself implementing it when using shrine for image uploading and playing around with some image cropping JS libs. Or do you think this is too specific to have it in here?

Let me know if I can help.

**Comment by janko-m** [comment]
Yes, I think it's definitely useful to have a cropping method. The implementation like you've given looks good, do you think you could make a PR?

I don't know cropping that well, what does the `!` do? Do you think it should be the default, and could it maybe be given as a keyword argument under a meaningful name? Also, I think it would be useful to have a `:gravity` option which defaults to "Center", in the same way `resize_to_fill` has.

**Comment by paulgoetze** [comment]
The `!` ensures that the virtual viewport of the cropped image is exactly of the defined size—even if the resulting cropped image has some "empty" space. This might be the case if you define a geometry bigger than the actual image or an offset that lies outside of the image.

Some helpful explanations are given here: http://www.imagemagick.org/Usage/crop/#crop

The `:gravity` definitely makes sense, good point.

Maybe the `!` isn’t important as default here, depending on what the crop functionality is actually used for, but to have it as an option might be useful, as you said. I guess we could also consider to add a `+repage` option.

I will investigate the cropping stuff a bit more during the next days and will then prepare a PR.
