### ISSUE TITLE
I think resize_to_fit does not preserve aspect ratio

### ISSUE THREAD

**Issue by ndbroadbent** [janko-m/image_processing#21]
In this line: https://github.com/janko-m/image_processing/blob/0ffd1807047507ea3ab0e9986cf1af18e6b083f4/lib/image_processing/mini_magick.rb#L37

`"#{width}x#{height}"` will stretch the image, so I don't think it should be called "resize to fit".

**Comment by janko-m** [comment]
Hmm, this should definitely not be the case, according to my tests and the official ImageMagick [documentation](https://www.imagemagick.org/script/command-line-processing.php#geometry).

<img width="882" alt="screen shot 2018-03-24 at 06 42 17" src="https://user-images.githubusercontent.com/795488/37860855-c26d220c-2f2e-11e8-86cf-1d1a1356dfcf.png">

**Comment by janko-m** [comment]
Can you post a self-contained example that reproduces the problem? For example:

```rb
require "image_processing/mini_magick"
require "open-uri"

image = open("https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Hopetoun_falls.jpg/1920px-Hopetoun_falls.jpg")
p MiniMagick::Image.new(image.path).dimensions

result = ImageProcessing::MiniMagick.source(image).resize_to_fit!(400, 400)
p MiniMagick::Image.new(result.path).dimensions
```
```
[1920, 1280]
[400, 267]
```

If it didn't preserve aspect ratio, then the result image should have had dimensions 400x400.

**Comment by ndbroadbent** [comment]
Oh sorry, you’re right! I was getting confused by own code. I have code that stretches the image for a PDF, and was using “#{width}x#{height}” in ImageMagick, and then stretching the final image in the PDF library. So I was just confused. Sorry about that!
