### ISSUE TITLE
Does the vips implementation support auto orientation?

### ISSUE THREAD

**Issue by mokolabs** [janko-m/image_processing#25]
I've got a question about image auto orientation.

So, right now in my app, during the `:cache` process, I'm checking for a non-standard orientation using FastImage. If the image does need to be reoriented, then I do that right in the `:cache` process.

That way, when the upload completes to the `:cache`, the image is already reoriented and it appears in the correct orientation immediately after upload. At the same time, the `:store` process doesn't need to do any reorientation since it already happened in the `:cache` process (because the `:cache` upload is passed along to the `:store` process after caching is complete).

Here's how the code looks:

```ruby
process(:cache) do |io, context|
  if context[:version].blank?
    if FastImage.new(io).orientation > 1
      io = ImageProcessing::MiniMagick
             .source(io)
             .auto_orient
             .call
    end
  end
end
```

Is there an equivalent implementation that would work with vips?

I tried a couple of obvious things like `.autorot`, but I'm unsure if this method -- which appears to be in libvips -- is bubbling up through ruby-vips and then image_processing correctly. Or maybe I'm just doing it wrong.

It could be nice to have a standard method call for auto orientation that works with both libraries.

**Comment by janko-m** [comment]
Yes, the `Vips::Image#autorot` ruby-vips method (which calls libvips' `vips_autorot()`) should be the correct way to autorotate the image. Calling `#autorot` on the ImageProcessing builder object should correctly delegate to `Vips::Image#autorot` via `#method_missing`.

However, as of https://github.com/janko-m/image_processing/commit/aeb9f2d97a1c2287da045f235f7f92a15d24af6d, both `ImageProcessing::MiniMagick` and `ImageProcessing::Vips` now automatically auto orient images after they're loaded (calling `#auto_orient` and `#autorot`) respectively, so there shouldn't be any need to autorotate manually anymore.

**Comment by janko-m** [comment]
In other words

```rb
process(:cache) do |io, context|
  if context[:version].blank?
    if FastImage.new(io).orientation > 1
      io = ImageProcessing::MiniMagick
             .source(io)
             .auto_orient
             .call
    end
  end
end
```

Could now become just

```rb
process(:cache) do |io, context|
  if context[:version].blank?
    if FastImage.new(io).orientation > 1
      io = ImageProcessing::MiniMagick.call(io)
    end
  end
end
```

**Comment by mokolabs** [comment]
Awesome!

So I just tried your code and it works with minimagick. But if I switch to vips, it doesn't work. 🤔 

Would this be the correct code for vips?

```ruby
process(:cache) do |io, context|
  if context[:version].blank?
    if FastImage.new(io).orientation > 1
      io = ImageProcessing::Vips.call(io)
    end
  end
end
```

**Comment by janko-m** [comment]
I cannot reproduce the issue, the following script shows a sample image being correctly rotated by both MiniMagick and Vips modules:

```rb
require "image_processing"
require "fastimage"
require "open-uri"

original            = open("http://stephensykes.com/images/ExifOrientation3.jpg")
minimagick_oriented = ImageProcessing::MiniMagick.call(original)
vips_oriented       = ImageProcessing::Vips.call(original)

File.write "page.html", <<-HTML
<div><h1>Original</h1><img src="file://#{original.path}" height=300></div>
<div><h1>ImageMagick</h1><img src="file://#{minimagick_oriented.path}" height=300></div>
<div><h1>libvips</h1><img src="file://#{vips_oriented.path}" height=300></div>
HTML

system "open page.html"

sleep 1000
```

An image can indicate its orientation in different places in its metadata. For example, take a look at the [`#auto_orient` implementation](https://github.com/eltiare/carrierwave-vips/blob/807c7e544aea3c44a061b7caf37fc8c330139e09/lib/carrierwave/vips.rb#L55-L74) from carrierwave-vips project before libvips added `vips_autorot()`. So maybe `vips_autorot()` implementation isn't handling your image correctly.

There are three places in total where you can tell ruby-vips/libvips to resize the image: (a) with `#autorot`, (b) by passing `:autorotate` to the loader, and (c) by passing `:auto_rotate` to the thumbnailer. You could try whether any of these three auto rotates the image:

```rb
result1 = ImageProcessing::Vips.call(image)
result2 = ImageProcessing::Vips.loader(autorotate: true, autorot: false).call(image)
result3 = ImageProcessing::Vips.loader(autorot: false).resize_to_limit(400, 400, auto_rotate: true).call(image)
```

If none of these work, you should probably report this issue to the libvips repository with the image that doesn't auto rotate.

**Comment by mokolabs** [comment]
Thanks, Janko.

I tried all of your code examples, but my test image was still failing.

The test image is `Landscape_2.jpg` from https://github.com/recurser/exif-orientation-examples and has an orientation value of `2`.

![landscape_2](https://user-images.githubusercontent.com/444/38062107-13fc3bf0-32a7-11e8-9aa0-9fa0d21b5bab.jpg)

So it's a horizontally flipped mirror image of orientation value 1, as you can see the diagram below:

![exif_orientations jpg](https://user-images.githubusercontent.com/444/38062439-c0c22916-32a8-11e8-8fc9-245d83ef1b95.gif)

Pretty puzzling. And then I remembered a [random comment from  jcupitt on the lipvips repo](https://github.com/jcupitt/libvips/issues/413):

> libvips just implements the rotation part of exif orientation, it doesn't do the mirroring.

> The reasoning was that all cameras just do upright / 90 degrees left / 90 degrees right / upside down, and none (as far as I know?) produce images with the left-right and top-bottom flip options which the spec allows. Without a real test case produced by a real device there didn't seem much point adding the feature.

So, auto orientation **_is_** working in the vips version, **but only for orientation values of 1, 3, 6, and 8.**

![exif_orientations jpg](https://user-images.githubusercontent.com/444/38062308-1736b97a-32a8-11e8-811f-822c020f4a60.gif)

And that's why my test image doesn't work in this case.

Going forward, since I'm dealing with a very large library of images taken using digital cameras from 1998 to 2018, I'm going to stick with the minimagick version (which is fine) just in case there are any photos with mirror orientations that need to be corrected.

Thanks for looking into this with me!

**Comment by wilg** [comment]
As mentioned on https://github.com/libvips/libvips/issues/413 iOS devices produce images with the flipped rotations (such as 5) if "Mirror Front Camera" is enabled in the settings, which reveals an issue with Rails' built in image analyzer not handling this and therefore returning incorrect dimensions https://github.com/rails/rails/issues/41940
