### ISSUE TITLE
Handling image profiles

### ISSUE THREAD

**Issue by janko-m** [janko-m/image_processing#28]
@janko-m:

> Also, do you think anything else needs to be done before releasing version 1.0?
> 
> On [dragonfly_libvips](https://github.com/tomasc/dragonfly_libvips/tree/master/vendor), [sharp](https://github.com/lovell/sharp/tree/master/lib/icc) and [imgproxy](https://github.com/DarthSim/imgproxy/blob/master/cmyk_profile.go) I saw assigning some default CMYK and ICC image profiles. I don't really understand it, but that's one thing that I'm still wondering whether ImageProcessing should also implement.

@mokolabs:

> Here's what the ImageOptim folks [recommend](https://imageoptim.com/color-profiles.html) on profiles:
> 
> > Save images in the sRGB profile with gamma 2.2, but don't embed any profile in the image. That's the most compatible and most efficient solution.
> 
> > Software that supports color profiles will assume that images without an embedded profile are in the sRGB profile. Software that doesn't support color profiles will use monitor's profile, which is most likely to be sRGB as well.
> 
> > By default, ImageOptim removes all color profiles. It's an obvious win for file size, and a good way to get consistent colors across different browsers, operating systems and devices.
> 
> > However, ImageOptim does not convert image pixels to the sRGB color space, because that's a slightly lossy operation. The color of the rare images that aren't in the sRGB color space will fade after the optimization (usually become a bit less saturated).
> 
> That seems like good advice to me.
> 
> We should assume most images will be in sRGB and just leave them alone. Developers can optionally strip profiles using the `.strip` method (though some may wish to keep them in place) or maybe do their own color profile conversion/injection.
> 
> For instance, in my case, I'm stripping profiles for all image versions except the largest image. The largest image keeps the original image profile.
> 
> That way, for example, if a photo was shot using the iPhone X (which can store its HDR images in the P3 colorspace) and then that photo is displayed on another device that supports the P3 colorspace (like the iMac Retina), the largest image will show the most accurate and vibrant colors.
> 
> The smaller versions won't include profiles, but it will be less important because those images will mostly be thumbnails anyway.

**Comment by mokolabs** [comment]
It would be problematic for me, yeah. And I suspect others.

From what I understand, `-thumbnail` is intended specifically for thumbnail-sized images which wouldn't benefit much from super acurate colors because they're generally tiny and viewed quickly (while scrolling a list or browsing through a page).

So, if we do it for all images by default, I think that would be heavy handed. Also, doesn't `-thumbnail` strip out EXIF tags too?

In my app, given the way image_processing currently works, I'm only preserving profiles on the two largest images (where true color fidelity would be most appreciated).

There's a bit of meta programming (so that I don't have to redeclare a ton of options for every image version), but you can see that I'm setting `strip` to true on the saver when the image height is less than 1024 pixels.

```ruby
process(:store) do |io, context|
  original = io.download
  mime_type = FastImage.type(original)

  extra      = resize_to(:fit, original, 2048, 2048, mime_type) 
  large      = resize_to(:fit, extra, 1024, 1024, mime_type)
  medium     = resize_to(:fit, large, 512, 512, mime_type)
  small      = resize_to(:fit, medium, 256, 256, mime_type)
  tiny       = resize_to(:fit, small, 16, 16, mime_type)

  thumb_1024 = resize_to(:fill, extra, 1024, 1024, mime_type)
  thumb_512  = resize_to(:fill, thumb_1024, 512, 512, mime_type)
  thumb_256  = resize_to(:fill, thumb_512, 256, 256, mime_type)
  thumb_128  = resize_to(:fill, thumb_256, 128, 128, mime_type)
  thumb_64   = resize_to(:fill, thumb_128, 64, 64, mime_type)
  thumb_16   = resize_to(:fill, thumb_64, 16, 16, mime_type)

  {original: original,
   extra: extra,
   large: large,
   medium: medium,
   small: small,
   tiny: tiny,
   thumb_1024: thumb_1024,
   thumb_512: thumb_512,
   thumb_256: thumb_256,
   thumb_128: thumb_128,
   thumb_64: thumb_64,
   thumb_16: thumb_16}       
end 

def resize_to(style, image, width, height, mime_type)
  # Set default image quality to 85
  # (but set :tiny previews to 100)
  quality = (height == 16 ? 100 : 85)

  # Strip tags and profiles from smaller images
  strip = (height < 1024 ? true : false)

  if mime_type.match? /jpeg|png/        
    ImageProcessing::Vips
      .source(image)
      .send("resize_to_#{style}".to_sym, width, height)
      .custom { |image|
         if mime_type.match? /jpeg/ and height > 16
           mask = Vips::Image.new_from_array [
                  [-1, -1, -1],
                  [-1, 32, -1],
                  [-1, -1, -1]], 24
          image.conv(mask)
         else
           image
         end }
      .saver(strip: strip, Q: quality, interlace: true)
      .call
  else
    ImageProcessing::MiniMagick
      .source(image)
      .send("resize_to_#{style}".to_sym, width, height)
      .quality(quality)
      .sharpen(height == 16 ? "0x0" : "0x1")
      .saver(strip: strip)
      .call
  end
end
```

**Comment by janko-m** [comment]
Thanks a lot for the insight, I can definitely see how this can cause undesireable backwards incompatibility. I'll revert back to `-resize`.

As explained [here](http://www.imagemagick.org/Usage/resize/#thumbnail), `-thumbnail` does have an additional advantage where it handles very large images much better, but I don't think that happens very often for user-uploaded images. I wish that `-resize` already incorporated those optimizations.

**Comment by mokolabs** [comment]
No problem.

What if we updated the strip option on `.saver()` to switch from `-resize` to `-thumbnail` whenever strip is set to `true` and then we also set strip to `true` by default?

**Comment by janko-m** [comment]
That's an interesting suggestion.

I found out more information about `-thumbnail`:

* it does not remove EXIF information
* it preserves color profiles (it strips the rest)
* it's highly recommended when processing TIFF files

So even though the documentation first says that it uses `-strip`, it doesn't actually anymore. The documentation says that if you want to strip everything, then you should use `-strip`. I don't know what other profiles are there other than color profiles (ICC), but this seems like the color profiles are the only ones actually affecting display.

To me `-thumbnail` now sounds like a good middle ground between performance and retaining information, what do you think?

**Comment by mokolabs** [comment]
Ha. Nice find, @janko-m!

Yeah, I just tested this myself with a sample photo from my iPhone X (with a P3 color profile) and can confirm that `-thumbnail` removes EXIF, GPS, and TIFF tags... but the profile is not removed.

So I think we're good!

That said, I do think we should still support `-resize` in some form (perhaps as an optional saver argument).

While I've always used a pattern of storing the original and then generating whatever versions I need, some people don't store the original and just keep whatever resized versions they generate. In that scenario, they may be surprised that the EXIF or GPS tags where removed and can't easily be recovered.

(Separately, I'm also wondering how switching to -thumbnail might impact the add_metadata plugin -- which, by default, if i understand the code correctly, will grab metadata from all the versions.)

So... to summarize my thoughts:

👍 for -thumbnail
👍 for an option to preserve all tags
❓ how will this impact metadata extraction? or other plugins?

**Comment by janko-m** [comment]
@mokolabs Thank you for correcting me on EXIF and other tags. I was checking this with `exiftool`, which apparently shows a lot of other data which isn't EXIF, so I misread the output when I was comparing.

Given what you've told me, I would like to implement a slight modification of your previous idea. I would like that we do `-resize` by default again, but switch to `-thumbnail` when `.saver(strip: true)` is given. So it's like what you said, but `:strip` wouldn't be `true` by default. The documentation would then advise to add `.saver(strip: true)` if EXIF data isn't necessary. There should probably be a way to use `-thumbnail` without `-strip`, though, in case the user wants to use `-thumbnail` but doesn't want to strip away the color profile. I'm not sure whether a saver option would be the right way to go for that.

To step back, as you said, resizing suddenly stripping EXIF/TIFF/other tags can break things, especially for folks who are not retaining the original image (btw, we're planning a new design of versions plugin where keeping the original image will be mandatory, read [this discussion](https://groups.google.com/d/msg/ruby-shrine/G-WooM709YY/pJ8LqG_tAgAJ) and https://github.com/shrinerb/shrine/issues/254 for more details). And I like to follow the principle of least surprise, so we'll switch back to `-resize`, and we can discuss how best to allow users to opt-in for `-thumbnail` separately.

> (Separately, I'm also wondering how switching to -thumbnail might impact the add_metadata plugin -- which, by default, if i understand the code correctly, will grab metadata from all the versions.)

Well, if the `add_metadata` extracts EXIF, then the versions wouldn't have EXIF data.

**Comment by mokolabs** [comment]
Sounds good!
