### ISSUE TITLE
Option to see final command

### ISSUE THREAD

**Issue by aried3r** [janko-m/image_processing#29]
Would you be open to have an additional method on `Processor` to print out the final command instead of executing it with `.call`? Much like `ActiveRecord::Relations`'s `.to_sql`.

It would make debugging a lot easier and I'm not sure if a dedicated logger would make much sense.

**Comment by janko-m** [comment]
FYI, in master `ImageProcessing::Builder#default_options` was renamed to just `#options` (this will part of the upcoming version 1.0). I will consider this question answered, but let me know if you had something else in mind.

**Comment by aried3r** [comment]
> I will consider this question answered, but let me know if you had something else in mind.

I'm good, thanks for the reply! 👍 I'll use what you suggested. :)
