### ISSUE TITLE
Invalid multibyte char (US-ASCII) error when running gemspec

### ISSUE THREAD

**Issue by paulgoetze** [janko-m/image_processing#3]
For some reason I couldn’t run the tests after checking out this repo:

Because of the `ć` character in the gemspec’s author name it failed with an "invalid multibyte char (US-ASCII)" error.

Adding `# encoding: utf-8` on top of the gemspec file fixes this.

I’m using C-Ruby v2.3.0. Might this be because there is no required Ruby version (>= 2.0) defined to handle utf-8 encoding by default (I never ran into this in gemspecs and I also have an `ö` in my name)?

**Comment by paulgoetze** [comment]
Ah, sorry, never mind, seemed to be some local utf-8 settings in my terminal. 
Should the encoding be added anyway?

**Comment by janko-m** [comment]
Hmm, I am testing image_processing only with Ruby 2.1 or higher, however I don't remember now why wouldn't 1.9.3 or higher be supported, for which the encoding header comment should be added. I think I should have it anyway.

**Comment by paulgoetze** [comment]
Versions >= v2.0 make sense, because keyword arguments are used in the code, which were introduced in Ruby 2.0. I added 2.0 and 2.3.0 to the travis.yml in my [fork](https://github.com/paulgoetze/image_processing/tree/fix-gemspec-encoding)—works fine. 

If you are ok with it I can open a PR.

**Comment by janko-m** [comment]
Makes sense, great, go for it :)
