### ISSUE TITLE
Add more documentation for 1.0?

### ISSUE THREAD

**Issue by mokolabs** [janko-m/image_processing#30]
If there's time, I'd like to take a pass at adding a bit more documentation for the 1.0 release.

Can I just open a branch and give it a go? Anything you guys would like to see?

(I enjoy technical writing and explaining things, so I think I could improve things.)

**Comment by janko-m** [comment]
@mokolabs That would be awesome! ❤️

Yes, feel free to open a branch. I don't have anything specific in mind, the only thing I have in my TODO list that I would like to write how you can convert each page of a PDF into a JPEG image (as I saw it come up once in Shrine and another time in CarrierWave), but I'll just write a quick "How to" guide in the [wiki](https://github.com/janko-m/image_processing/wiki).

**Comment by mokolabs** [comment]
Okay, cool. I'll start on that tomorrow.

**Comment by janko-m** [comment]
The blog post for the upcoming ImageProcessing 1.0 is ready 💪 (to be published when we release 1.0)

**Comment by mokolabs** [comment]
Awesome. Is there a way I can preview that?

(Should finally have time to write some more docs later today)

**Comment by janko-m** [comment]
@mokolabs I haven't yet figured out how to expose drafts on my Jekyll blog, so I copied it into a [gist](https://gist.github.com/janko-m/62b0774413d36b8ef0134e20c7b297ef) (the only thing that's missing are the two images illustrating auto-rotation and sharpening). Let me know what you think!

**Comment by mokolabs** [comment]
@janko-m Here's a fork of your gist. Hope it helps!

https://gist.github.com/mokolabs/62025844956fc93031daf3eb2a27b02f
