### ISSUE TITLE
Implement image composition

### ISSUE THREAD

**Issue by daniel-illi** [janko-m/image_processing#35]
Is there any chance you will implement methods for image compositioning?

As provided by:
ruby-vips: http://www.rubydoc.info/gems/ruby-vips/Vips/Image:composite2
Imagemagick: https://www.imagemagick.org/script/compose.php

**Comment by janko-m** [comment]
Yeah, I would definitely like to support compositioning. Let's first see how we would do it without any special API, and then we can discuss how a special API could look like.

## MiniMagick

MiniMagick has a `MiniMagick::Image#composite` method, which is just a thin wrapper around the `composite` command. We're not going to use that, as ImageProcessing is not using `MiniMagick::Image`, and also it's building a `convert` command (soon it will be a `magick` command), so we should use the `-composite` operator as an alternative to a `composite` command. [This article](http://www.imagemagick.org/Usage/compose/#compose) shows the difference:

```
composite {overlay} {background} [{mask}] [-compose {method}]            {result}
convert   {background} {overlay} [{mask}] [-compose {method}] -composite {result}
```

[This article](http://www.imagemagick.org/Usage/layers/#composite) shows some usage examples. So, at the moment the composition could be done with:

```rb
background # background image
overlay    # overlay image
mask     # optional mask

ImageProcessing::MiniMagick
  .source(background)
  .append(overlay.path)
  .append(mask.path) # optional
  .define("compose:args=50,50") # compose arguments
  .composite
  .call
```

### `#composite`

I'm voting for adding a `#composite` method, which without arguments will just add `-composite` to the command (as it currently does), but with arguments would have the following API:

```rb
ImageProcessing::MiniMagick
  .source(background)
  .composite(overlay, mask: mask, args: "50,50")
  .call
```

The main argument is the "overlay" image, the `:mask` parameter is an optional mask, and any other options are interpreted as "compose arguments" (added via `-define "compose:<key>=<value>`).

## Vips

It seems that for libvips we don't need any special API, people can just use`Vips::Image#composite2` directly:

```rb
ImageProcessing::Vips
  .source(background)
  .composite2(overlay, ...)
  .call
```

It would probably be nice to provide automatic conversion of a file into a `Vips::Image` object for the `overlay`, as currently it would have to be done manually:

```rb
  .composite2(Vips::Image.new_from_file(overlay.path), ...)
```

**Comment by janko-m** [comment]
@daniel-illi Would you like to give it a shot?
