### ISSUE TITLE
Image rotation

### ISSUE THREAD

**Issue by sandstrom** [janko-m/image_processing#40]
Nice gem! Would be even better if one could rotate images. 😄 

Something like this should do it for VIPS (at least for ruby-vips 0.3.8, may be different in more recent versions).

```ruby
# Note that this only handles rotations of 90, 180 and 270, 
# but that should be sufficient for most use-cases. Rotating to other numers
# get's really weird and is a very rare type of image operation.
def rotate(degrees, original_vips_image)
      normalized_degrees = degrees % 360 # normalize on 360º (will also turn -90 into 270, which is neat)
      n = normalized_degrees / 90 # will round to integer, i.e. n will be [0..4]

      vips_image = original_vips_image
      n.times { vips_image = vips_image.rot90 }
      vips_image
end
```

Let me know what you think!

**Comment by sandstrom** [comment]
Yes, that would work!

I haven't looked that much at this lib yet, but is the idea to provide a uniform api for image manipulation across vips and image-magick?

If so perhaps a standardized api looking something like this would be useful:

```ruby
def rotate(degrees, vips_image)
  normalized_degrees = degrees % 360 # normalize on 360º (will also turn -90 into 270, which is neat)
  angle = normalized_degrees / 90 * 90 # force one of 0, 90, 180, 270

  vips_image.rot("d#{angle}".to_sym)
end
```

Where the implementation of `rotate` would differ between VIPS and image-magick, but would offer the same public api.

*But perhaps the goal isn't to provide a uniform api, in that case what exists already should be enough. For our use-case we'll only use VIPS anyways.*

**Comment by janko-m** [comment]
> I haven't looked that much at this lib yet, but is the idea to provide a uniform api for image manipulation across vips and image-magick?

Yes, that's right. Only the common image processing functionality, that is.

> If so perhaps a standardized api looking something like this would be useful:

Oh, I understand now what you meant. Yes, that sounds like a great idea, and the implementation looks good, though I would omit the normalization and perhaps use `vips_similarity()` in case the given number of degrees isn't a multiple of 90.

Would you like to send a pull request for this?

**Comment by mokolabs** [comment]
That would be a nice addition.

Are you thinking it would work like this?

```ruby
ImageProcessing::MiniMagick
  .rotate(90)

ImageProcessing::Vips
  .rotate(90)
```

**Comment by sandstrom** [comment]
@janko-m I think we should stick with multiples of 90. I'd say that covers 95% of the use-cases. When thinking of tools where image rotation is possible (mobile apps, online photo galleries, Apple Preview, etc) most of them have rotation in 90° steps, but very few have rotation to any angle.

Also, when you rotate to a non-90° angle you need to specify the background color to fill the newly created whitespace.

@mokolabs Yes! 😄 

I may be able to PR, but not in the next few weeks unfortunately (busy times). Would probably coincide with us switching our internal image processing library over to `image_processing`

**Comment by janko-m** [comment]
> Would you be okay with doing only 90° steps?

Yeah, I actually wanted to suggest that for now we just make `#rotate` raise an exception if `degrees` is not a multiple of 90, and later we can add support for other angles if it gets requested.

> I may be able to PR, but not in the next few weeks unfortunately (busy times).

No problem. @mokolabs Would you like to take a stab at it?
