### ISSUE TITLE
Access image properties

### ISSUE THREAD

**Issue by sandstrom** [janko-m/image_processing#41]
Awesome gem! 🏆 

A method to access image data would be useful. For example image dimensions, and perhaps exif data too.

For VIPS, something along these lines should work.

```ruby
def dimensions
  { :width => vips_image.x_size, :height => vips_image.y_size }
end
```

But may make more sense with a general `image_properties` method, that would return a hash with more than just width/height.

What do you think?

**Comment by janko-m** [comment]
> Awesome gem! 🏆

Thanks! 😃 

> A method to access image data would be useful. For example image dimensions, and perhaps exif data too.

I would prefer to keep the scope of this gem to be only for processing. There is no need to add this behaviour, because you should already be able to access any image properties using `Vips::Image` directly:

```rb
image = Vips::Image.new_from_file("/path/to/image")

image.width  #=> 600
image.height #=> 800
image.size   #=> [600, 800]

exif_fields = image.get_fields
  .grep(/^exif-ifd\d-/)
  .inject({}) { |hash, name| hash.merge!(name[/^exif-ifd\d-(\w+)/, 1] => image.get(name)) }

exif_fields #=>
# {
#   "Make"=>"Apple (Apple, ASCII, 6 components, 6 bytes)",
#   "Model"=>"iPhone 4S (iPhone 4S, ASCII, 10 components, 10 bytes)",
#   "Orientation"=>"1 (Top-left, Short, 1 components, 2 bytes)",
#   "XResolution"=>"72/1 (72, Rational, 1 components, 8 bytes)",
#   "YResolution"=>"72/1 (72, Rational, 1 components, 8 bytes)",
#   "ResolutionUnit"=>"2 (Inch, Short, 1 components, 2 bytes)",
#   ....
# }
```

If you want to do conditional processing, the `#custom` ImageProcessing method yields the `Vips::Image` object to the block, so in that case you don't have to instantiate it directly.

**Comment by sandstrom** [comment]
> I would prefer to keep the scope of this gem to be only for processing.

@janko-m That's a valid point (I disagree, but you're the author so it makes sense that you decide on the scope). We currently access VIPS directly for this data, so we can certainly keep some of that around.

Maybe the scope will expand over time, and that image data access will be added in the future. 🙏

**Comment by janko-m** [comment]
> That's a valid point (I disagree, but you're the author so it makes sense that you decide on the scope).

I would still like to understand what would in your opinion be the advantage of `ImageProcessing::Vips` offering the functionality for accessing image properties. And how do you imagine the API to look like? 

The reason why I don't see this functionality in ImageProcessing gem is that all `ImageProcessing::Vips` and `ImageProcessing::MiniMagick` methods are designed to build options for the underlying processor for applying transformations to the image once a "terminal method" is called.

An `#image_properties` method in my opinion breaks out of this design, because it doesn't return a `Vips::Image` object, it returns a hash of properties. I do like the idea of being able to retrieve a hash of properties, I just think that this method is better added to ruby-vips gem itself rather than ImageProcessing gem.

**Comment by sandstrom** [comment]
Got it, let's leave this out for now (it's easy enough to do outside this gem).

**Comment by sandstrom** [comment]
@janko Hello again! 😄 

Just wanted to resurface this idea and see if you are open to reconsidering? 

I noticed that Rails ActiveStorage is relying on your gem for processing, which is awesome! 👏 

Also noticed that the ActiveStorage `ImageAnalyzer`, which extracts image height/width metadata, is using ImageMagick (via `MiniMagick`).

https://github.com/rails/rails/blob/477ec2675d2321eeaa0f5330ab5f3e12b09cb361/activestorage/lib/active_storage/analyzer/image_analyzer.rb#L20

Wouldn't it be awesome if this gem could extract dimensions (width/height) from images, that way rails could use your gem for that facility, instead of using MiniMagick directly (source link above).

Today, someone who wants to use vips for e.g. rotation still need to pull in image magick to extract width/height.

In VIPS it shouldn't be much more than `x, y = vips_image.x_size, vips_image.y_size` to extract these values.

Let me know what you think! 😄

**Comment by janko** [comment]
@sandstrom Hi 👋 

My opinion on this still stands. ImageMagick and libvips return image data in different format, so it's better to use MiniMagick/ruby-vips directly to access this data. On the ImageProcessing side it would require new classes and new API, which I wouldn't want to design and maintain, and is not in the intended scope of this project (retrieving image data isn't "processing").

Active Storage should add support for ruby-vips, like [Shrine has](https://github.com/shrinerb/shrine/blob/15bd63223ec35003b644720d47f752b123876830/lib/shrine/plugins/store_dimensions.rb#L134-L142).

**Comment by sandstrom** [comment]
@janko I'm not sure that I understand ("return image data in different format"). Dimensions should be just a tuple of width/height, no? But I guess I'm missing something, obviously you'll know this stuff much better than me, since you authored two very popular libraries 😄 

I understand that it doesn't fit 100% into the current API, but perhaps something simple could work?

```ruby
# usage example
ImageProcessing::Vips.dimensions(file) #=> [100, 200]

# implementation example
module ImageProcessing
  module Vips
    extend Chainable

    # Returns image dimensions
    def self.dimensions(file)
      ::Vips::Image.new_from_file(file.path).size
    rescue ::Vips::Error
      [nil, nil]
    end

    # Returns whether the given image file is processable.
    def self.valid_image?(file)
      # …
  end
end  
```

It would be true to the underlying idea for this library, but would extend to the (very common) processing operation of extracting width/height (seems like it would also allow Shrine to delegate to ImageProcessing for this task, instead of accessing directly). 

> "Currently, existing attachment gems (like Paperclip, CarrierWave, Refile, Dragonfly, ActiveStorage, and others) implement their own custom image helper methods. But why? That's not very DRY, is it?"

But I totally understand if you don't want to make changes, it's all up to you obviously! Either way I think this is a wonderful 💎 !

**Comment by wilg** [comment]
I was after this too, because Rails' built in analyzer incorrectly handles orientation, uses ImageMagick, and I use VIPS.
