### ISSUE TITLE
Using libvips < 8.6+ on Ubuntu ?

### ISSUE THREAD

**Issue by paulbernhard** [janko-m/image_processing#44]
Hi,

thanks for sharing _Shrine_ and _ImageProcessing_, i'm using them regularily in my applications. The added support for _libvips_ in _ImageProcessing_ is great, but i encountered a problem on my production server (Ubuntu 16.04).

Since i changed from _MiniMagick_ to _libvips_, i get the following error on my production server :

```
Could not spawn process for application /home/deploy/hvmbs_app/current: The application encountered the following error: image_processing/vips requires libvips 8.6+ (RuntimeError)

vips -v
vips-8.2.2-Sat Jan 30 17:12:08 UTC 2016
```

Obviously my version of _libvips_ is not sufficient for the requirements of _ImageProcessing_, but appearently the last stable release of _libvips is 8.4+_. 

Is it possible to use a lower version of _libvips_ with _ImageProcessing_ ? 

Thanks !

**Comment by renchap** [comment]
I wrote a blog post to create up-to-date `libvips` packages on Debian, I think you can build them for Ubuntu the same way: 
http://www.renchap.com/blog/post/building_recent_libvips_on_debian/

**Comment by janko-m** [comment]
> thanks for sharing Shrine and ImageProcessing, i'm using them regularily in my applications.

That's great to hear, you're welcome!

> Is it possible to use a lower version of libvips with ImageProcessing ?

Unfortunately, libvips 8.6 is the lowest version we're able to support to achieve the current functionality.

## libvips 8.5

libvips 8.5 added [`Vips::Image.thumbnail`](https://www.rubydoc.info/gems/ruby-vips/Vips/Image#thumbnail-class_method), which allows effortless generation of thumbnails using dimensions.

Without it we would have to use [`Vips::Image#resize`](https://www.rubydoc.info/gems/ruby-vips/Vips/Image#resize-instance_method), which only accepts a scale factor. So, we'd have to translate from the dimensions the user specified to the scale factor, and also support the different `#resize_*` semantics, which is not trivial – see the code in [vips-thumbnail](https://github.com/ioquatix/vips-thumbnail/blob/4ca0782883d7c706ef6c90818ce0087989d5f9b9/lib/vips/thumbnail/resizer.rb#L59-L118) or [carrierwave-vips](https://github.com/eltiare/carrierwave-vips/blob/master/lib/carrierwave/vips.rb#L255-L265) gems.

Even if we somehow implement thumbnails using `#resize`, the new `.thumbnail` function is still much faster, more memory-efficient, and produces better quality than `#resize` – see https://github.com/ioquatix/vips-thumbnail/issues/1#issue-255672841. For these reasons I didn't find supporting a `#resize` implementation worthwhile.

## libvips 8.6

libvips 8.6 added [`Vips::Image#thumbnail`]. The original `.thumbnail` didn't allow applying any functions before the thumbnailing, which isn't very flexible and breaks ImageProcessing's design of being able to chain any operation in whichever order. The new `#thumbnail` allows resizing an image that has already been loaded, so you can also perform processing before calling `#thumbnail`. This fits into the ImageProcessing design.

## Solution

To get libvips 8.6 on Ubuntu you can try [building from source]()https://github.com/jcupitt/libvips/wiki/Build-for-Ubuntu#building-from-source) or finding an alternative apt repository which has libvips 8.6 already built on your version of Ubuntu.

I know that neither of these two options are ideal, but as I explained it's not feasible for us to support older libvips versions. All we can provide is better documentation on how to install libvips 8.6 (in case something is missing from the official docs). @mokolabs has also been working on a Heroku buildpack for installing libvips, see https://github.com/janko-m/image_processing/issues/32.
