### ISSUE TITLE
LoadError: Could not open library 'glib-2.0'

### ISSUE THREAD

**Issue by mbajur** [janko-m/image_processing#45]
I'm not sure if that's a fault of `image_processing` gem (actually i think it's not but i have no idea where to ask this) but i'm not able to use vips lib via `image_processing` while it's possible to do this directly.

I've written a code dedicated to extracting first frame from animated gif to a jpg file. It looks like that:

```
    system 'wget https://umaar.com/assets/images/dev-tips/screenshot-capture.gif'

    ImageProcessing::Vips.source(File.open('screenshot-capture.gif'))
                         .loader(page: 1)
                         .convert('jpg')
                         .saver(background: 255, quality: 100)
                         .resize_to_limit!(100, 100)
```

And running this throws:

```
LoadError: Could not open library 'glib-2.0': Error loading shared library glib-2.0: No such file or directory.
Could not open library 'libglib-2.0.so': Error loading shared library libglib-2.0.so: No such file or directory
/prismo/vendor/bundle/ruby/2.5.0/gems/ffi-1.9.25/lib/ffi/library.rb:145:in `block in ffi_lib'
/prismo/vendor/bundle/ruby/2.5.0/gems/ffi-1.9.25/lib/ffi/library.rb:99:in `map'
/prismo/vendor/bundle/ruby/2.5.0/gems/ffi-1.9.25/lib/ffi/library.rb:99:in `ffi_lib'
/prismo/vendor/bundle/ruby/2.5.0/gems/ruby-vips-2.0.12/lib/vips.rb:28:in `<module:GLib>'
/prismo/vendor/bundle/ruby/2.5.0/gems/ruby-vips-2.0.12/lib/vips.rb:13:in `<main>'
```

On the other hand, i'm totally able to run any `vips` command in bash and it works just fine. I can't reproduce the ruby code above in pure bash command 1:1 (is there any way to tell `image_processing` to show me how the given methods chain converts to terminal command?). I have tested it using [this dockerfile](https://github.com/felixbuenemann/vips-alpine/blob/master/Dockerfile), [this dockerfile](https://github.com/codechimp-io/vips-alpine/blob/master/Dockerfile) and also using an [official alpine vips package](https://pkgs.alpinelinux.org/package/edge/testing/x86/vips)

I'm not sure what details could be handy in here but if there is anything i can do to help you help me, please let me know. Also, if that's nothing obvious, i can create a basic docker setup for this for you to make it easy to reproduce the issue.

**Comment by renchap** [comment]
If you are running on a debian-based OS, you need the `libvips-dev` package. More details here: https://github.com/libvips/ruby-vips/issues/176

**Comment by janko-m** [comment]
Thanks for taking the effort to come up with a self-contained example. This error is coming from the `ruby-vips` gem, so if @renchap's answer doesn't solve your problem, you should ask on the `ruby-vips` project.

> I can't reproduce the ruby code above in pure bash command 1:1 (is there any way to tell image_processing to show me how the given methods chain converts to terminal command?)

Unlike MiniMagick, ruby-vips isn't running shell commands, it's executing libvips functions via C. You can retrieve the "accumulator object", which is `Vips::Image` instance, by removing the bang and adding `#call(save: false)`:

```rb
image = ImageProcessing::Vips.source(File.open('screenshot-capture.gif'))
  .loader(page: 1)
  .convert('jpg')
  .saver(background: 255, quality: 100)
  .resize_to_limit(100, 100)
  .call(save: false)

image #=> #<Vips::Image>
```

The `Vips::Image` object is like a lazy pipeline of libvips functions, because when you call `#write_to_file` on it, the functions get executed. However, I don't know if `ruby-vips` gives you the ability to access them. If you want that feature, you should also ask on the `ruby-vips` issue tracker.

**Comment by mbajur** [comment]
Thank you guys! I'm on alpine and i tried to use it with both `vips-dev` and even `vips-tools` but still no luck. I'm moving it to ruby-vips then :)
