### ISSUE TITLE
Rails doesn't use Vips for variant

### ISSUE THREAD

**Issue by a-ta-ta** [janko-m/image_processing#46]
Hello!

Thank you very much for this gem and support of vips! Seems awesome!

I think I've missed something, but can't figure out what's wrong.
I've done like it was described:
1) added gem `'image_processing', '~> 1.2'` to the Gemfile
2) added `config.active_storage.variant_processor = :vips` to `application.rb`
3) when I use irb:
```
Loading production environment (Rails 5.2.1)
irb(main):001:0> pipeline = ImageProcessing::Vips
```
output says:
`=> ImageProcessing::Vips`

And  still I get errors for variants:
I, [2018-11-21T18:08:00.568681 #1242]  INFO  Completed 500 Internal Server Error in 334ms (ActiveRecord: 0.3ms)
F, [2018-11-21T18:08:00.569907 #1242] FATAL 
F, [2018-11-21T18:08:00.569956 #1242] FATAL  MiniMagick::Error (`mogrify -resize-and-pad [320, 240] /tmp/mini_magick20181121-1242-1ejlv6a.jpg` failed with error:
mogrify: unrecognized option `-resize-and-pad' @ error/mogrify.c/MogrifyImageCommand/5525.
):
F, [2018-11-21T18:08:00.569983 #1242] FATAL 
F, [2018-11-21T18:08:00.570019 #1242] FATAL  mini_magick (4.9.2) lib/mini_magick/shell.rb:17:in   mini_magick (4.9.2) lib/mini_magick/tool.rb:90:in `  mini_magick (4.9.2) lib/mini_magick/tool.rb:38:in   mini_magick (4.9.2) lib/mini_magick/image.rb:564:in `mog  activestorage (5.2.1) app/models/active_storage/variation.rb:59:in `block (2 levels) in transform'

Seems like it still uses minimagick. Could you please help me?

**Comment by janko-m** [comment]
Rails 5.2 doesn't yet use the `image_processing` gem (I tried to get it in before Rails 5.2 was released, but they wouldn't accept new features anymore at that point). So it will be available in Rails 6.0, but for now it's only available on `master`.
