### ISSUE TITLE
Converting PSD results in two files for PNG output

### ISSUE THREAD

**Issue by walterdavis** [janko-m/image_processing#9]
Freshly installed the dependencies through Homebrew, using latest version of the gem. I first noticed the issue in a Shrine uploader using versions, so I made this cut-down test script to narrow things down. In Shrine, the problem bubbles up to prevent the PNG version from being found (and thus moved and saved) during the promote phase.

```rb
require "image_processing/mini_magick"
include ImageProcessing::MiniMagick
original = File.open("/Users/waltd/Pictures/at-at-in-chicago.psd")
converted = convert(original, "png")
system "open #{File.dirname(converted.path)}"
```

The result is that in the folder there are two files, one suffixed with -0.png and the other with -1.png. I have tried this with a range of different PSDs, some of which I made, and some of which were client-provided. In all other formats that I have tried, the PNG file is correctly created as a single file.

At the lowest level, if I navigate to the file and use `identify` from ImageMagick to look at the source file, I see two different output lines for the file with the same filename and [0] and [1] after each. I've seen how Paperclip deals with this in conversions, by taking the output of `identify` and using the zeroth index if the return is not a single line. Is that possible here?

**Comment by janko-m** [comment]
@walterdavis Yes, that is actually the behaviour of ImageMagick itself, when you convert from a multi-layer format (PSD, PDF, ...) to a single-layer format (JPEG, PNG, ...).

The original MiniMagick behaviour was that all calls to a `MiniMagick::Image` should result in a modified `MiniMagick::Image` instance, so there was no room to handle multi-image outputs. However, if you only need to convert the 1st page of the PSD, the `#convert` method actually accepts the page argument (which is delegated to `MiniMagick::Image#format`), so you should be able to do:

```rb
convert(original, "png", 0)
```
